add keycloak-related feature flags
cancogen-virus-seq/portal pull request #232
Opened 2022-04-04 16:22 UTC by caravinci

2022-04-04 16:28 UTC, caravinci reviewed
quick read-through of changes

2022-04-04 16:28 UTC, caravinci commented on next.config.js
> +    NEXT_PUBLIC_ENABLE_REGISTRATION: process.env.NEXT_PUBLIC_ENABLE_REGISTRATION,
Get the Env vars

2022-04-04 16:28 UTC, caravinci commented on global/config.ts
> +      (publicConfig.NEXT_PUBLIC_ENABLE_REGISTRATION || '').toLowerCase() === 'true' || false,
parse them as boolean

2022-04-04 16:28 UTC, caravinci commented on components/pages/explorer/RepoTable/index.tsx
> +          customHeaderContent={NEXT_PUBLIC_ENABLE_DOWNLOADS && DownloadButton}
only display the `download` button if enabled

this could also be useful for `singularity` maintenance.

2022-04-04 16:28 UTC, caravinci commented on components/pages/login/PageContent.tsx
> +              <p>
show registration button if enabled

2022-04-04 16:28 UTC, caravinci commented on components/pages/login/PageContent.tsx
> +            <li>
show login button if enabled

2022-04-04 16:28 UTC, caravinci commented on components/Footer.tsx
> +          {(NEXT_PUBLIC_ENABLE_LOGIN || NEXT_PUBLIC_ENABLE_REGISTRATION) && !token && (
show the link in the footer if either of the keycloak flags is on

2022-04-04 16:28 UTC, caravinci commented on pages/login/index.tsx
>      }),
redirect to root instead of login, if user attempts a restricted feature while both are disabled.

2022-06-03 20:20 UTC, b-f-chan commented
@caravinci - Can/should this be merged?  Just doing some cleanup, no rush

2022-06-03 20:34 UTC, caravinci commented
These are some feature flags I'm adding in case we need a nuclear "disable all login and or registration ui stuff", but it wasn't attached to any ticket/spec. It was a result of the Java vulnerabilities that may have affected Keycloak a few weeks ago.

Needs review, and it's just a good to have; but it's not a requirement.

2022-06-12 17:59 UTC, joneubank requested changes
Please add placeholder variables for these flags in `env.schema` and set them as true in `env.test`

Ideally this would also be documented somewhere, a practice we've been lax on before but we should start now. Can you find a place in a Readme to add a table that lists:
* all feature flags in application
* environment variable name
* default value
* description of what the flag does

2022-06-12 18:03 UTC, caravinci commented
good suggestions! will do.

thanks @joneubank

2022-08-24 14:18 UTC, joneubank approved these changes

2022-08-25 14:21 UTC, merged